# Generated by Django 3.0.5 on 2020-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
    ]
