# Generated by Django 3.0.5 on 2020-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('forgn_b', models.IntegerField()),
                ('forgn_s', models.IntegerField()),
                ('forgn_n', models.IntegerField()),
                ('private_b', models.IntegerField()),
                ('private_s', models.IntegerField()),
                ('private_n', models.IntegerField()),
                ('inst_sum_b', models.IntegerField()),
                ('inst_sum_s', models.IntegerField()),
                ('inst_sum_n', models.IntegerField()),
                ('trust_b', models.IntegerField()),
                ('trust_s', models.IntegerField()),
                ('trust_n', models.IntegerField()),
                ('pension_b', models.IntegerField()),
                ('pension_s', models.IntegerField()),
                ('pension_n', models.IntegerField()),
                ('etc_inst_b', models.IntegerField()),
                ('etc_inst_s', models.IntegerField()),
                ('etc_inst_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('cls_prc', models.FloatField()),
                ('trd_qty', models.IntegerField()),
                ('trd_amt', models.IntegerField()),
                ('etf_nav', models.FloatField()),
                ('spread', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('per', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('pcr', models.FloatField(blank=True, null=True)),
                ('psr', models.FloatField(blank=True, null=True)),
                ('divid_yield', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('strt_prc', models.FloatField()),
                ('high_prc', models.FloatField()),
                ('low_prc', models.FloatField()),
                ('cls_prc', models.FloatField()),
                ('trd_qty', models.FloatField()),
                ('trd_amt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('comm_stk_qty', models.IntegerField()),
                ('pref_stk_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('strt_prc', models.IntegerField()),
                ('high_prc', models.IntegerField()),
                ('low_prc', models.IntegerField()),
                ('cls_prc', models.IntegerField()),
                ('adj_prc', models.IntegerField(blank=True, null=True)),
                ('trd_qty', models.FloatField()),
                ('trd_amt', models.FloatField(blank=True, null=True)),
                ('shtsale_trd_qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('stk_kind', models.CharField(max_length=50)),
                ('mkt_gb', models.CharField(max_length=50)),
                ('mkt_cap', models.IntegerField()),
                ('mkt_cap_size', models.CharField(max_length=50)),
                ('frg_hlg', models.FloatField()),
                ('mgt_gb', models.CharField(max_length=50)),
            ],
        ),
    ]
