# Generated by Django 3.0.5 on 2020-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_monitorstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinOHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('openp', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
