# Generated by Django 3.0.5 on 2020-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_buysell_etf_factor_index_marketcapital_ohlcv_stockinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcv',
            name='adj_prc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
